[
  # TODO: Gnome specific stuff - move somewhere else
  ./dconf
  ./gtk.nix

  ./alacritty.nix
  ./atuin.nix
  ./bat.nix
  ./claude
  ./fish
  ./tmux
  ./waybar
  ./direnv.nix
  ./dunst.nix
  ./firefox.nix
  ./zen-browser.nix
  ./git.nix
  ./gitui.nix
  ./helix.nix
  ./idea-copilot.nix
  ./kitty.nix
  ./minecraft.nix
  ./neovim.nix
  ./rust.nix
  ./starship.nix
  ./walker.nix
  ./vicinae.nix
  ./waystt.nix
  # ./wofi.nix
  ./zellij.nix
  ./zoxide.nix
  ./low-battery-alert.nix
  ./screenshot-journal.nix
  ./video-journal.nix
  ./swaylock.nix
  ./webapps.nix
  ./niri-screen-time.nix
  ./obsidian.nix
]
