# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fb325da5-2df3-4d63-805a-34fd4ce021cb";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-b434fc68-7488-4b24-9586-64873440d712".device = "/dev/disk/by-uuid/b434fc68-7488-4b24-9586-64873440d712";

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/0EC0-04C0";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/848a0d20-aa8a-40e3-a78b-69710323ae5d";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
