[
  ./adguard.nix
  ./audiobookshelf.nix
  ./caddy.nix
  ./calibre-web.nix
  ./firefly-iii.nix
  ./gitea.nix
  ./homepage.nix
  ./memos.nix
  ./navidrome.nix
  ./netdata.nix
  ./nfs.nix
  ./ollama.nix
  ./paperless.nix
  ./restic.nix
  ./rss.nix
  ./scrutiny.nix
  ./security.nix
  ./tailscale.nix
  ./selfhosted.nix
  ./traggo.nix
  ./vpn.nix
  ./watchyourlan.nix
]
