# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  modulesPath,
  pkgs,
  nixos-hardware,
  ...
}: {
  imports = [
    # nixos-hardware.nixosModules.framework-12th-gen-intel # Disabled due to conflict with CachyOS kernel
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # boot.kernelPackages = pkgs.linuxPackages_zen; # Overridden by CachyOS kernel
  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod"];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e33d79b0-4de1-47d3-a3fe-ab53c3f7f390";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-b1731fc9-3d03-44aa-83b7-9061aba94621".device = "/dev/disk/by-uuid/b1731fc9-3d03-44aa-83b7-9061aba94621";

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/4A19-036A";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/8feea14d-3406-4e2f-9608-f36ad9082e4b";}
  ];
}
